describe('Calculator has number buttons that can be clicked', function() {
  beforeEach(function() {
    // runs before each test in the block
    cy.visit('/')
    cy.get('#on-off').click()
  })
  it('Can click number buttons and returns a value', function() {
    cy.get('#num-0')
      .click()
    cy.get('#calc-disp').should('have.value', '00')
    cy.get('#num-00')
      .click()
    cy.get('#calc-disp').should('have.value', '0000')
    cy.get('#num-1')
      .click()
    cy.get('#calc-disp').should('have.value', '00001')
    cy.get('#num-2')
      .click()
    cy.get('#calc-disp').should('have.value', '000012')
    cy.get('#num-3')
      .click()
    cy.get('#calc-disp').should('have.value', '0000123')
    cy.get('#num-4')
      .click()
    cy.get('#calc-disp').should('have.value', '00001234')
    cy.get('#num-5')
      .click()
    cy.get('#calc-disp').should('have.value', '000012345')
    cy.get('#num-6')
      .click()
    cy.get('#calc-disp').should('have.value', '0000123456')
    cy.get('#num-7')
      .click()
    cy.get('#calc-disp').should('have.value', '00001234567')
    cy.get('#num-8')
      .click()
    cy.get('#calc-disp').should('have.value', '000012345678')
    cy.get('#num-9')
      .click()
    cy.get('#calc-disp').should('have.value', '0000123456789')
  })
})
